[pytest]
markers =
    smoke: marker for smoke tests
    regression: marker for regression tests
    win10
    login_guest:
    add_to_cart: добавляем товар в корзину
    no_message: должны отсутстовать сообщения
    login_page_from: открытие формы авторизации
    new: